      SUBROUTINE EXDBSQLITE
      IMPLICIT NONE
C----------
C BASE $Id: exdbs.f 2750 2019-08-15 01:23:04Z mshettles521 $
C----------
C  EXTERNAL REFERENCES FOR THE Q-FAMILY DATA BASE CONNECTION CODE.
C----------
      REAL TPA1,BA1,CFVOL,BFVOL,STDIST
      REAL INGROW,TPAIN,TPASUM,HTAVE,TPATOT,PRBSTK,SUMTPA,SUMPCT,
     >     PASPCT,BESTTPA,BESTPCT,AVEHT,PASTPA
      INTEGER BURNYEAR, NUMPTS,M,NOYEAR,MECHYEAR,PCTBURN,WTHTAVE,TOT,
     >     NTALLY,IYEAR,PCTNONE,PCTMECH
      CHARACTER*47 HABTYP
      CHARACTER*7 SERIES
      CHARACTER*2 SPECCD
      REAL RDANUW
      INTEGER IDANUW
      CHARACTER*1 CDANUW
C----------
C  ENTRY DBSSTATS
C----------      
      ENTRY  DBSSTATS(SPECCD,TPA1,BA1,CFVOL,BFVOL,STDIST)
C----------
C  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
C----------
        IF(.TRUE.)RETURN
        CDANUW = SPECCD
        RDANUW = TPA1
        RDANUW = BA1
        RDANUW = CFVOL
        RDANUW = BFVOL
        RDANUW = STDIST
      RETURN 
C----------
C  ENTRY DBSSPRT
C----------      
      ENTRY  DBSSPRT(SPECCD,TPASUM,HTAVE,TPATOT,
     &  WTHTAVE,TOT,IYEAR)
C----------
C  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
C----------
        IF(.TRUE.)RETURN
        CDANUW = SPECCD
        RDANUW = TPASUM
        RDANUW = HTAVE
        RDANUW = TPATOT
        RDANUW = WTHTAVE
        IDANUW = TOT
        IDANUW = IYEAR
      RETURN 
C----------
C  ENTRY DBSSITEPREP
C----------      
      ENTRY  DBSSITEPREP(NOYEAR,MECHYEAR,BURNYEAR,PCTNONE,
     & PCTMECH,PCTBURN)
C----------
C  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
C----------
        IF(.TRUE.)RETURN
        IDANUW = NOYEAR
        IDANUW = MECHYEAR
        IDANUW = BURNYEAR
        IDANUW = PCTNONE
        IDANUW = PCTMECH
        IDANUW = PCTBURN
      RETURN 
C----------
C  ENTRY DBSPLOTHAB
C----------      
      ENTRY  DBSPLOTHAB(NUMPTS,HABTYP,SERIES,M)
C----------
C  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
C----------
        IF(.TRUE.)RETURN
        IDANUW = NUMPTS
        CDANUW = HABTYP
        CDANUW = SERIES
        IDANUW = M
      RETURN 
C----------
C  ENTRY DBSTALLY
C----------      
      ENTRY  DBSTALLY(PRBSTK,NTALLY,SPECCD,SUMTPA,SUMPCT,BESTTPA,
     & BESTPCT,AVEHT,PASTPA,PASPCT,IYEAR)
C----------
C  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
C----------
        IF(.TRUE.)RETURN
        RDANUW = PRBSTK
        IDANUW = NTALLY
        CDANUW = SPECCD
        RDANUW = SUMTPA
        RDANUW = SUMPCT
        RDANUW = BESTTPA
        RDANUW = BESTPCT
        RDANUW = AVEHT
        RDANUW = PASTPA
        RDANUW = PASPCT
        IDANUW = IYEAR
      RETURN 
C----------
C  ENTRY DBSINGROW
C----------      
      ENTRY  DBSINGROW(IYEAR,INGROW,SPECCD,TPAIN)
C----------
C  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
C----------
        IF(.TRUE.)RETURN
        IDANUW = IYEAR
        RDANUW = INGROW
        CDANUW = SPECCD
        RDANUW = TPAIN
      RETURN 
C
      END

